export const LetterCounterparts = {
  // Mathematical Alphanumeric Symbols Block
  // https://charbase.com/block/mathematical-alphanumeric-symbols
  '𝐀': { code: 'U+1D400', counterpart: 'A' },
  '𝐁': { code: 'U+1D401', counterpart: 'B' },
  '𝐂': { code: 'U+1D402', counterpart: 'C' },
  '𝐃': { code: 'U+1D403', counterpart: 'D' },
  '𝐄': { code: 'U+1D404', counterpart: 'E' },
  '𝐅': { code: 'U+1D405', counterpart: 'F' },
  '𝐆': { code: 'U+1D406', counterpart: 'G' },
  '𝐇': { code: 'U+1D407', counterpart: 'H' },
  '𝐈': { code: 'U+1D408', counterpart: 'I' },
  '𝐉': { code: 'U+1D409', counterpart: 'J' },
  '𝐊': { code: 'U+1D40A', counterpart: 'K' },
  '𝐋': { code: 'U+1D40B', counterpart: 'L' },
  '𝐌': { code: 'U+1D40C', counterpart: 'M' },
  '𝐍': { code: 'U+1D40D', counterpart: 'N' },
  '𝐎': { code: 'U+1D40E', counterpart: 'O' },
  '𝐏': { code: 'U+1D40F', counterpart: 'P' },
  '𝐐': { code: 'U+1D410', counterpart: 'Q' },
  '𝐑': { code: 'U+1D411', counterpart: 'R' },
  '𝐒': { code: 'U+1D412', counterpart: 'S' },
  '𝐓': { code: 'U+1D413', counterpart: 'T' },
  '𝐔': { code: 'U+1D414', counterpart: 'U' },
  '𝐕': { code: 'U+1D415', counterpart: 'V' },
  '𝐖': { code: 'U+1D416', counterpart: 'W' },
  '𝐗': { code: 'U+1D417', counterpart: 'X' },
  '𝐘': { code: 'U+1D418', counterpart: 'Y' },
  '𝐙': { code: 'U+1D419', counterpart: 'Z' },
  '𝐚': { code: 'U+1D41A', counterpart: 'A' },
  '𝐛': { code: 'U+1D41B', counterpart: 'B' },
  '𝐜': { code: 'U+1D41C', counterpart: 'C' },
  '𝐝': { code: 'U+1D41D', counterpart: 'D' },
  '𝐞': { code: 'U+1D41E', counterpart: 'E' },
  '𝐟': { code: 'U+1D41F', counterpart: 'F' },
  '𝐠': { code: 'U+1D420', counterpart: 'G' },
  '𝐡': { code: 'U+1D421', counterpart: 'H' },
  '𝐢': { code: 'U+1D422', counterpart: 'I' },
  '𝐣': { code: 'U+1D423', counterpart: 'J' },
  '𝐤': { code: 'U+1D424', counterpart: 'K' },
  '𝐥': { code: 'U+1D425', counterpart: 'L' },
  '𝐦': { code: 'U+1D426', counterpart: 'M' },
  '𝐧': { code: 'U+1D427', counterpart: 'N' },
  '𝐨': { code: 'U+1D428', counterpart: 'O' },
  '𝐩': { code: 'U+1D429', counterpart: 'P' },
  '𝐪': { code: 'U+1D42A', counterpart: 'Q' },
  '𝐫': { code: 'U+1D42B', counterpart: 'R' },
  '𝐬': { code: 'U+1D42C', counterpart: 'S' },
  '𝐭': { code: 'U+1D42D', counterpart: 'T' },
  '𝐮': { code: 'U+1D42E', counterpart: 'U' },
  '𝐯': { code: 'U+1D42F', counterpart: 'V' },
  '𝐰': { code: 'U+1D430', counterpart: 'W' },
  '𝐱': { code: 'U+1D431', counterpart: 'X' },
  '𝐲': { code: 'U+1D432', counterpart: 'Y' },
  '𝐳': { code: 'U+1D433', counterpart: 'Z' },
  '𝐴': { code: 'U+1D434', counterpart: 'A' },
  '𝐵': { code: 'U+1D435', counterpart: 'B' },
  '𝐶': { code: 'U+1D436', counterpart: 'C' },
  '𝐷': { code: 'U+1D437', counterpart: 'D' },
  '𝐸': { code: 'U+1D438', counterpart: 'E' },
  '𝐹': { code: 'U+1D439', counterpart: 'F' },
  '𝐺': { code: 'U+1D43A', counterpart: 'G' },
  '𝐻': { code: 'U+1D43B', counterpart: 'H' },
  '𝐼': { code: 'U+1D43C', counterpart: 'I' },
  '𝐽': { code: 'U+1D43D', counterpart: 'J' },
  '𝐾': { code: 'U+1D43E', counterpart: 'K' },
  '𝐿': { code: 'U+1D43F', counterpart: 'L' },
  '𝑀': { code: 'U+1D440', counterpart: 'M' },
  '𝑁': { code: 'U+1D441', counterpart: 'N' },
  '𝑂': { code: 'U+1D442', counterpart: 'O' },
  '𝑃': { code: 'U+1D443', counterpart: 'P' },
  '𝑄': { code: 'U+1D444', counterpart: 'Q' },
  '𝑅': { code: 'U+1D445', counterpart: 'R' },
  '𝑆': { code: 'U+1D446', counterpart: 'S' },
  '𝑇': { code: 'U+1D447', counterpart: 'T' },
  '𝑈': { code: 'U+1D448', counterpart: 'U' },
  '𝑉': { code: 'U+1D449', counterpart: 'V' },
  '𝑊': { code: 'U+1D44A', counterpart: 'W' },
  '𝑋': { code: 'U+1D44B', counterpart: 'X' },
  '𝑌': { code: 'U+1D44C', counterpart: 'Y' },
  '𝑍': { code: 'U+1D44D', counterpart: 'Z' },
  '𝑎': { code: 'U+1D44E', counterpart: 'A' },
  '𝑏': { code: 'U+1D44F', counterpart: 'B' },
  '𝑐': { code: 'U+1D450', counterpart: 'C' },
  '𝑑': { code: 'U+1D451', counterpart: 'D' },
  '𝑒': { code: 'U+1D452', counterpart: 'E' },
  '𝑓': { code: 'U+1D453', counterpart: 'F' },
  '𝑔': { code: 'U+1D454', counterpart: 'G' },
  '𝑖': { code: 'U+1D456', counterpart: 'I' },
  '𝑗': { code: 'U+1D457', counterpart: 'J' },
  '𝑘': { code: 'U+1D458', counterpart: 'K' },
  '𝑙': { code: 'U+1D459', counterpart: 'L' },
  '𝑚': { code: 'U+1D45A', counterpart: 'M' },
  '𝑛': { code: 'U+1D45B', counterpart: 'N' },
  '𝑜': { code: 'U+1D45C', counterpart: 'O' },
  '𝑝': { code: 'U+1D45D', counterpart: 'P' },
  '𝑞': { code: 'U+1D45E', counterpart: 'Q' },
  '𝑟': { code: 'U+1D45F', counterpart: 'R' },
  '𝑠': { code: 'U+1D460', counterpart: 'S' },
  '𝑡': { code: 'U+1D461', counterpart: 'T' },
  '𝑢': { code: 'U+1D462', counterpart: 'U' },
  '𝑣': { code: 'U+1D463', counterpart: 'V' },
  '𝑤': { code: 'U+1D464', counterpart: 'W' },
  '𝑥': { code: 'U+1D465', counterpart: 'X' },
  '𝑦': { code: 'U+1D466', counterpart: 'Y' },
  '𝑧': { code: 'U+1D467', counterpart: 'Z' },
  '𝑨': { code: 'U+1D468', counterpart: 'A' },
  '𝑩': { code: 'U+1D469', counterpart: 'B' },
  '𝑪': { code: 'U+1D46A', counterpart: 'C' },
  '𝑫': { code: 'U+1D46B', counterpart: 'D' },
  '𝑬': { code: 'U+1D46C', counterpart: 'E' },
  '𝑭': { code: 'U+1D46D', counterpart: 'F' },
  '𝑮': { code: 'U+1D46E', counterpart: 'G' },
  '𝑯': { code: 'U+1D46F', counterpart: 'H' },
  '𝑰': { code: 'U+1D470', counterpart: 'I' },
  '𝑱': { code: 'U+1D471', counterpart: 'J' },
  '𝑲': { code: 'U+1D472', counterpart: 'K' },
  '𝑳': { code: 'U+1D473', counterpart: 'L' },
  '𝑴': { code: 'U+1D474', counterpart: 'M' },
  '𝑵': { code: 'U+1D475', counterpart: 'N' },
  '𝑶': { code: 'U+1D476', counterpart: 'O' },
  '𝑷': { code: 'U+1D477', counterpart: 'P' },
  '𝑸': { code: 'U+1D478', counterpart: 'Q' },
  '𝑹': { code: 'U+1D479', counterpart: 'R' },
  '𝑺': { code: 'U+1D47A', counterpart: 'S' },
  '𝑻': { code: 'U+1D47B', counterpart: 'T' },
  '𝑼': { code: 'U+1D47C', counterpart: 'U' },
  '𝑽': { code: 'U+1D47D', counterpart: 'V' },
  '𝑾': { code: 'U+1D47E', counterpart: 'W' },
  '𝑿': { code: 'U+1D47F', counterpart: 'X' },
  '𝒀': { code: 'U+1D480', counterpart: 'Y' },
  '𝒁': { code: 'U+1D481', counterpart: 'Z' },
  '𝒂': { code: 'U+1D482', counterpart: 'A' },
  '𝒃': { code: 'U+1D483', counterpart: 'B' },
  '𝒄': { code: 'U+1D484', counterpart: 'C' },
  '𝒅': { code: 'U+1D485', counterpart: 'D' },
  '𝒆': { code: 'U+1D486', counterpart: 'E' },
  '𝒇': { code: 'U+1D487', counterpart: 'F' },
  '𝒈': { code: 'U+1D488', counterpart: 'G' },
  '𝒉': { code: 'U+1D489', counterpart: 'H' },
  '𝒊': { code: 'U+1D48A', counterpart: 'I' },
  '𝒋': { code: 'U+1D48B', counterpart: 'J' },
  '𝒌': { code: 'U+1D48C', counterpart: 'K' },
  '𝒍': { code: 'U+1D48D', counterpart: 'L' },
  '𝒎': { code: 'U+1D48E', counterpart: 'M' },
  '𝒏': { code: 'U+1D48F', counterpart: 'N' },
  '𝒐': { code: 'U+1D490', counterpart: 'O' },
  '𝒑': { code: 'U+1D491', counterpart: 'P' },
  '𝒒': { code: 'U+1D492', counterpart: 'Q' },
  '𝒓': { code: 'U+1D493', counterpart: 'R' },
  '𝒔': { code: 'U+1D494', counterpart: 'S' },
  '𝒕': { code: 'U+1D495', counterpart: 'T' },
  '𝒖': { code: 'U+1D496', counterpart: 'U' },
  '𝒗': { code: 'U+1D497', counterpart: 'V' },
  '𝒘': { code: 'U+1D498', counterpart: 'W' },
  '𝒙': { code: 'U+1D499', counterpart: 'X' },
  '𝒚': { code: 'U+1D49A', counterpart: 'Y' },
  '𝒛': { code: 'U+1D49B', counterpart: 'Z' },
  '𝒜': { code: 'U+1D49C', counterpart: 'A' },
  '𝒞': { code: 'U+1D49E', counterpart: 'C' },
  '𝒟': { code: 'U+1D49F', counterpart: 'D' },
  '𝒢': { code: 'U+1D4A2', counterpart: 'G' },
  '𝒥': { code: 'U+1D4A5', counterpart: 'J' },
  '𝒦': { code: 'U+1D4A6', counterpart: 'K' },
  '𝒩': { code: 'U+1D4A9', counterpart: 'N' },
  '𝒪': { code: 'U+1D4AA', counterpart: 'O' },
  '𝒫': { code: 'U+1D4AB', counterpart: 'P' },
  '𝒬': { code: 'U+1D4AC', counterpart: 'Q' },
  '𝒮': { code: 'U+1D4AE', counterpart: 'S' },
  '𝒯': { code: 'U+1D4AF', counterpart: 'T' },
  '𝒰': { code: 'U+1D4B0', counterpart: 'U' },
  '𝒱': { code: 'U+1D4B1', counterpart: 'V' },
  '𝒲': { code: 'U+1D4B2', counterpart: 'W' },
  '𝒳': { code: 'U+1D4B3', counterpart: 'X' },
  '𝒴': { code: 'U+1D4B4', counterpart: 'Y' },
  '𝒵': { code: 'U+1D4B5', counterpart: 'Z' },
  '𝒶': { code: 'U+1D4B6', counterpart: 'A' },
  '𝒷': { code: 'U+1D4B7', counterpart: 'B' },
  '𝒸': { code: 'U+1D4B8', counterpart: 'C' },
  '𝒹': { code: 'U+1D4B9', counterpart: 'D' },
  '𝒻': { code: 'U+1D4BB', counterpart: 'F' },
  '𝒽': { code: 'U+1D4BD', counterpart: 'H' },
  '𝒾': { code: 'U+1D4BE', counterpart: 'I' },
  '𝒿': { code: 'U+1D4BF', counterpart: 'J' },
  '𝓀': { code: 'U+1D4C0', counterpart: 'K' },
  '𝓁': { code: 'U+1D4C1', counterpart: 'L' },
  '𝓂': { code: 'U+1D4C2', counterpart: 'M' },
  '𝓃': { code: 'U+1D4C3', counterpart: 'N' },
  '𝓅': { code: 'U+1D4C5', counterpart: 'P' },
  '𝓆': { code: 'U+1D4C6', counterpart: 'Q' },
  '𝓇': { code: 'U+1D4C7', counterpart: 'R' },
  '𝓈': { code: 'U+1D4C8', counterpart: 'S' },
  '𝓉': { code: 'U+1D4C9', counterpart: 'T' },
  '𝓊': { code: 'U+1D4CA', counterpart: 'U' },
  '𝓋': { code: 'U+1D4CB', counterpart: 'V' },
  '𝓌': { code: 'U+1D4CC', counterpart: 'W' },
  '𝓍': { code: 'U+1D4CD', counterpart: 'X' },
  '𝓎': { code: 'U+1D4CE', counterpart: 'Y' },
  '𝓏': { code: 'U+1D4CF', counterpart: 'Z' },
  '𝓐': { code: 'U+1D4D0', counterpart: 'A' },
  '𝓑': { code: 'U+1D4D1', counterpart: 'B' },
  '𝓒': { code: 'U+1D4D2', counterpart: 'C' },
  '𝓓': { code: 'U+1D4D3', counterpart: 'D' },
  '𝓔': { code: 'U+1D4D4', counterpart: 'E' },
  '𝓕': { code: 'U+1D4D5', counterpart: 'F' },
  '𝓖': { code: 'U+1D4D6', counterpart: 'G' },
  '𝓗': { code: 'U+1D4D7', counterpart: 'H' },
  '𝓘': { code: 'U+1D4D8', counterpart: 'I' },
  '𝓙': { code: 'U+1D4D9', counterpart: 'J' },
  '𝓚': { code: 'U+1D4DA', counterpart: 'K' },
  '𝓛': { code: 'U+1D4DB', counterpart: 'L' },
  '𝓜': { code: 'U+1D4DC', counterpart: 'M' },
  '𝓝': { code: 'U+1D4DD', counterpart: 'N' },
  '𝓞': { code: 'U+1D4DE', counterpart: 'O' },
  '𝓟': { code: 'U+1D4DF', counterpart: 'P' },
  '𝓠': { code: 'U+1D4E0', counterpart: 'Q' },
  '𝓡': { code: 'U+1D4E1', counterpart: 'R' },
  '𝓢': { code: 'U+1D4E2', counterpart: 'S' },
  '𝓣': { code: 'U+1D4E3', counterpart: 'T' },
  '𝓤': { code: 'U+1D4E4', counterpart: 'U' },
  '𝓥': { code: 'U+1D4E5', counterpart: 'V' },
  '𝓦': { code: 'U+1D4E6', counterpart: 'W' },
  '𝓧': { code: 'U+1D4E7', counterpart: 'X' },
  '𝓨': { code: 'U+1D4E8', counterpart: 'Y' },
  '𝓩': { code: 'U+1D4E9', counterpart: 'Z' },
  '𝓪': { code: 'U+1D4EA', counterpart: 'A' },
  '𝓫': { code: 'U+1D4EB', counterpart: 'B' },
  '𝓬': { code: 'U+1D4EC', counterpart: 'C' },
  '𝓭': { code: 'U+1D4ED', counterpart: 'D' },
  '𝓮': { code: 'U+1D4EE', counterpart: 'E' },
  '𝓯': { code: 'U+1D4EF', counterpart: 'F' },
  '𝓰': { code: 'U+1D4F0', counterpart: 'G' },
  '𝓱': { code: 'U+1D4F1', counterpart: 'H' },
  '𝓲': { code: 'U+1D4F2', counterpart: 'I' },
  '𝓳': { code: 'U+1D4F3', counterpart: 'J' },
  '𝓴': { code: 'U+1D4F4', counterpart: 'K' },
  '𝓵': { code: 'U+1D4F5', counterpart: 'L' },
  '𝓶': { code: 'U+1D4F6', counterpart: 'M' },
  '𝓷': { code: 'U+1D4F7', counterpart: 'N' },
  '𝓸': { code: 'U+1D4F8', counterpart: 'O' },
  '𝓹': { code: 'U+1D4F9', counterpart: 'P' },
  '𝓺': { code: 'U+1D4FA', counterpart: 'Q' },
  '𝓻': { code: 'U+1D4FB', counterpart: 'R' },
  '𝓼': { code: 'U+1D4FC', counterpart: 'S' },
  '𝓽': { code: 'U+1D4FD', counterpart: 'T' },
  '𝓾': { code: 'U+1D4FE', counterpart: 'U' },
  '𝓿': { code: 'U+1D4FF', counterpart: 'V' },
  '𝔀': { code: 'U+1D500', counterpart: 'W' },
  '𝔁': { code: 'U+1D501', counterpart: 'X' },
  '𝔂': { code: 'U+1D502', counterpart: 'Y' },
  '𝔃': { code: 'U+1D503', counterpart: 'Z' },
  '𝔄': { code: 'U+1D504', counterpart: 'A' },
  '𝔅': { code: 'U+1D505', counterpart: 'B' },
  '𝔇': { code: 'U+1D507', counterpart: 'D' },
  '𝔈': { code: 'U+1D508', counterpart: 'E' },
  '𝔉': { code: 'U+1D509', counterpart: 'F' },
  '𝔊': { code: 'U+1D50A', counterpart: 'G' },
  '𝔍': { code: 'U+1D50D', counterpart: 'J' },
  '𝔎': { code: 'U+1D50E', counterpart: 'K' },
  '𝔏': { code: 'U+1D50F', counterpart: 'L' },
  '𝔐': { code: 'U+1D510', counterpart: 'M' },
  '𝔑': { code: 'U+1D511', counterpart: 'N' },
  '𝔒': { code: 'U+1D512', counterpart: 'O' },
  '𝔓': { code: 'U+1D513', counterpart: 'P' },
  '𝔔': { code: 'U+1D514', counterpart: 'Q' },
  '𝔖': { code: 'U+1D516', counterpart: 'S' },
  '𝔗': { code: 'U+1D517', counterpart: 'T' },
  '𝔘': { code: 'U+1D518', counterpart: 'U' },
  '𝔙': { code: 'U+1D519', counterpart: 'V' },
  '𝔚': { code: 'U+1D51A', counterpart: 'W' },
  '𝔛': { code: 'U+1D51B', counterpart: 'X' },
  '𝔜': { code: 'U+1D51C', counterpart: 'Y' },
  '𝔞': { code: 'U+1D51E', counterpart: 'A' },
  '𝔟': { code: 'U+1D51F', counterpart: 'B' },
  '𝔠': { code: 'U+1D520', counterpart: 'C' },
  '𝔡': { code: 'U+1D521', counterpart: 'D' },
  '𝔢': { code: 'U+1D522', counterpart: 'E' },
  '𝔣': { code: 'U+1D523', counterpart: 'F' },
  '𝔤': { code: 'U+1D524', counterpart: 'G' },
  '𝔥': { code: 'U+1D525', counterpart: 'H' },
  '𝔦': { code: 'U+1D526', counterpart: 'I' },
  '𝔧': { code: 'U+1D527', counterpart: 'J' },
  '𝔨': { code: 'U+1D528', counterpart: 'K' },
  '𝔩': { code: 'U+1D529', counterpart: 'L' },
  '𝔪': { code: 'U+1D52A', counterpart: 'M' },
  '𝔫': { code: 'U+1D52B', counterpart: 'N' },
  '𝔬': { code: 'U+1D52C', counterpart: 'O' },
  '𝔭': { code: 'U+1D52D', counterpart: 'P' },
  '𝔮': { code: 'U+1D52E', counterpart: 'Q' },
  '𝔯': { code: 'U+1D52F', counterpart: 'R' },
  '𝔰': { code: 'U+1D530', counterpart: 'S' },
  '𝔱': { code: 'U+1D531', counterpart: 'T' },
  '𝔲': { code: 'U+1D532', counterpart: 'U' },
  '𝔳': { code: 'U+1D533', counterpart: 'V' },
  '𝔴': { code: 'U+1D534', counterpart: 'W' },
  '𝔵': { code: 'U+1D535', counterpart: 'X' },
  '𝔶': { code: 'U+1D536', counterpart: 'Y' },
  '𝔷': { code: 'U+1D537', counterpart: 'Z' },
  '𝔸': { code: 'U+1D538', counterpart: 'A' },
  '𝔹': { code: 'U+1D539', counterpart: 'B' },
  '𝔻': { code: 'U+1D53B', counterpart: 'D' },
  '𝔼': { code: 'U+1D53C', counterpart: 'E' },
  '𝔽': { code: 'U+1D53D', counterpart: 'F' },
  '𝔾': { code: 'U+1D53E', counterpart: 'G' },
  '𝕀': { code: 'U+1D540', counterpart: 'I' },
  '𝕁': { code: 'U+1D541', counterpart: 'J' },
  '𝕂': { code: 'U+1D542', counterpart: 'K' },
  '𝕃': { code: 'U+1D543', counterpart: 'L' },
  '𝕄': { code: 'U+1D544', counterpart: 'M' },
  '𝕆': { code: 'U+1D546', counterpart: 'O' },
  '𝕊': { code: 'U+1D54A', counterpart: 'S' },
  '𝕋': { code: 'U+1D54B', counterpart: 'T' },
  '𝕌': { code: 'U+1D54C', counterpart: 'U' },
  '𝕍': { code: 'U+1D54D', counterpart: 'V' },
  '𝕎': { code: 'U+1D54E', counterpart: 'W' },
  '𝕏': { code: 'U+1D54F', counterpart: 'X' },
  '𝕐': { code: 'U+1D550', counterpart: 'Y' },
  '𝕒': { code: 'U+1D552', counterpart: 'A' },
  '𝕓': { code: 'U+1D553', counterpart: 'B' },
  '𝕔': { code: 'U+1D554', counterpart: 'C' },
  '𝕕': { code: 'U+1D555', counterpart: 'D' },
  '𝕖': { code: 'U+1D556', counterpart: 'E' },
  '𝕗': { code: 'U+1D557', counterpart: 'F' },
  '𝕘': { code: 'U+1D558', counterpart: 'G' },
  '𝕙': { code: 'U+1D559', counterpart: 'H' },
  '𝕚': { code: 'U+1D55A', counterpart: 'I' },
  '𝕛': { code: 'U+1D55B', counterpart: 'J' },
  '𝕜': { code: 'U+1D55C', counterpart: 'K' },
  '𝕝': { code: 'U+1D55D', counterpart: 'L' },
  '𝕞': { code: 'U+1D55E', counterpart: 'M' },
  '𝕟': { code: 'U+1D55F', counterpart: 'N' },
  '𝕠': { code: 'U+1D560', counterpart: 'O' },
  '𝕡': { code: 'U+1D561', counterpart: 'P' },
  '𝕢': { code: 'U+1D562', counterpart: 'Q' },
  '𝕣': { code: 'U+1D563', counterpart: 'R' },
  '𝕤': { code: 'U+1D564', counterpart: 'S' },
  '𝕥': { code: 'U+1D565', counterpart: 'T' },
  '𝕦': { code: 'U+1D566', counterpart: 'U' },
  '𝕧': { code: 'U+1D567', counterpart: 'V' },
  '𝕨': { code: 'U+1D568', counterpart: 'W' },
  '𝕩': { code: 'U+1D569', counterpart: 'X' },
  '𝕪': { code: 'U+1D56A', counterpart: 'Y' },
  '𝕫': { code: 'U+1D56B', counterpart: 'Z' },
  '𝕬': { code: 'U+1D56C', counterpart: 'A' },
  '𝕭': { code: 'U+1D56D', counterpart: 'B' },
  '𝕮': { code: 'U+1D56E', counterpart: 'C' },
  '𝕯': { code: 'U+1D56F', counterpart: 'D' },
  '𝕰': { code: 'U+1D570', counterpart: 'E' },
  '𝕱': { code: 'U+1D571', counterpart: 'F' },
  '𝕲': { code: 'U+1D572', counterpart: 'G' },
  '𝕳': { code: 'U+1D573', counterpart: 'H' },
  '𝕴': { code: 'U+1D574', counterpart: 'I' },
  '𝕵': { code: 'U+1D575', counterpart: 'J' },
  '𝕶': { code: 'U+1D576', counterpart: 'K' },
  '𝕷': { code: 'U+1D577', counterpart: 'L' },
  '𝕸': { code: 'U+1D578', counterpart: 'M' },
  '𝕹': { code: 'U+1D579', counterpart: 'N' },
  '𝕺': { code: 'U+1D57A', counterpart: 'O' },
  '𝕻': { code: 'U+1D57B', counterpart: 'P' },
  '𝕼': { code: 'U+1D57C', counterpart: 'Q' },
  '𝕽': { code: 'U+1D57D', counterpart: 'R' },
  '𝕾': { code: 'U+1D57E', counterpart: 'S' },
  '𝕿': { code: 'U+1D57F', counterpart: 'T' },
  '𝖀': { code: 'U+1D580', counterpart: 'U' },
  '𝖁': { code: 'U+1D581', counterpart: 'V' },
  '𝖂': { code: 'U+1D582', counterpart: 'W' },
  '𝖃': { code: 'U+1D583', counterpart: 'X' },
  '𝖄': { code: 'U+1D584', counterpart: 'Y' },
  '𝖅': { code: 'U+1D585', counterpart: 'Z' },
  '𝖆': { code: 'U+1D586', counterpart: 'A' },
  '𝖇': { code: 'U+1D587', counterpart: 'B' },
  '𝖈': { code: 'U+1D588', counterpart: 'C' },
  '𝖉': { code: 'U+1D589', counterpart: 'D' },
  '𝖊': { code: 'U+1D58A', counterpart: 'E' },
  '𝖋': { code: 'U+1D58B', counterpart: 'F' },
  '𝖌': { code: 'U+1D58C', counterpart: 'G' },
  '𝖍': { code: 'U+1D58D', counterpart: 'H' },
  '𝖎': { code: 'U+1D58E', counterpart: 'I' },
  '𝖏': { code: 'U+1D58F', counterpart: 'J' },
  '𝖐': { code: 'U+1D590', counterpart: 'K' },
  '𝖑': { code: 'U+1D591', counterpart: 'L' },
  '𝖒': { code: 'U+1D592', counterpart: 'M' },
  '𝖓': { code: 'U+1D593', counterpart: 'N' },
  '𝖔': { code: 'U+1D594', counterpart: 'O' },
  '𝖕': { code: 'U+1D595', counterpart: 'P' },
  '𝖖': { code: 'U+1D596', counterpart: 'Q' },
  '𝖗': { code: 'U+1D597', counterpart: 'R' },
  '𝖘': { code: 'U+1D598', counterpart: 'S' },
  '𝖙': { code: 'U+1D599', counterpart: 'T' },
  '𝖚': { code: 'U+1D59A', counterpart: 'U' },
  '𝖛': { code: 'U+1D59B', counterpart: 'V' },
  '𝖜': { code: 'U+1D59C', counterpart: 'W' },
  '𝖝': { code: 'U+1D59D', counterpart: 'X' },
  '𝖞': { code: 'U+1D59E', counterpart: 'Y' },
  '𝖟': { code: 'U+1D59F', counterpart: 'Z' },
  '𝖠': { code: 'U+1D5A0', counterpart: 'A' },
  '𝖡': { code: 'U+1D5A1', counterpart: 'B' },
  '𝖢': { code: 'U+1D5A2', counterpart: 'C' },
  '𝖣': { code: 'U+1D5A3', counterpart: 'D' },
  '𝖤': { code: 'U+1D5A4', counterpart: 'E' },
  '𝖥': { code: 'U+1D5A5', counterpart: 'F' },
  '𝖦': { code: 'U+1D5A6', counterpart: 'G' },
  '𝖧': { code: 'U+1D5A7', counterpart: 'H' },
  '𝖨': { code: 'U+1D5A8', counterpart: 'I' },
  '𝖩': { code: 'U+1D5A9', counterpart: 'J' },
  '𝖪': { code: 'U+1D5AA', counterpart: 'K' },
  '𝖫': { code: 'U+1D5AB', counterpart: 'L' },
  '𝖬': { code: 'U+1D5AC', counterpart: 'M' },
  '𝖭': { code: 'U+1D5AD', counterpart: 'N' },
  '𝖮': { code: 'U+1D5AE', counterpart: 'O' },
  '𝖯': { code: 'U+1D5AF', counterpart: 'P' },
  '𝖰': { code: 'U+1D5B0', counterpart: 'Q' },
  '𝖱': { code: 'U+1D5B1', counterpart: 'R' },
  '𝖲': { code: 'U+1D5B2', counterpart: 'S' },
  '𝖳': { code: 'U+1D5B3', counterpart: 'T' },
  '𝖴': { code: 'U+1D5B4', counterpart: 'U' },
  '𝖵': { code: 'U+1D5B5', counterpart: 'V' },
  '𝖶': { code: 'U+1D5B6', counterpart: 'W' },
  '𝖷': { code: 'U+1D5B7', counterpart: 'X' },
  '𝖸': { code: 'U+1D5B8', counterpart: 'Y' },
  '𝖹': { code: 'U+1D5B9', counterpart: 'Z' },
  '𝖺': { code: 'U+1D5BA', counterpart: 'A' },
  '𝖻': { code: 'U+1D5BB', counterpart: 'B' },
  '𝖼': { code: 'U+1D5BC', counterpart: 'C' },
  '𝖽': { code: 'U+1D5BD', counterpart: 'D' },
  '𝖾': { code: 'U+1D5BE', counterpart: 'E' },
  '𝖿': { code: 'U+1D5BF', counterpart: 'F' },
  '𝗀': { code: 'U+1D5C0', counterpart: 'G' },
  '𝗁': { code: 'U+1D5C1', counterpart: 'H' },
  '𝗂': { code: 'U+1D5C2', counterpart: 'I' },
  '𝗃': { code: 'U+1D5C3', counterpart: 'J' },
  '𝗄': { code: 'U+1D5C4', counterpart: 'K' },
  '𝗅': { code: 'U+1D5C5', counterpart: 'L' },
  '𝗆': { code: 'U+1D5C6', counterpart: 'M' },
  '𝗇': { code: 'U+1D5C7', counterpart: 'N' },
  '𝗈': { code: 'U+1D5C8', counterpart: 'O' },
  '𝗉': { code: 'U+1D5C9', counterpart: 'P' },
  '𝗊': { code: 'U+1D5CA', counterpart: 'Q' },
  '𝗋': { code: 'U+1D5CB', counterpart: 'R' },
  '𝗌': { code: 'U+1D5CC', counterpart: 'S' },
  '𝗍': { code: 'U+1D5CD', counterpart: 'T' },
  '𝗎': { code: 'U+1D5CE', counterpart: 'U' },
  '𝗏': { code: 'U+1D5CF', counterpart: 'V' },
  '𝗐': { code: 'U+1D5D0', counterpart: 'W' },
  '𝗑': { code: 'U+1D5D1', counterpart: 'X' },
  '𝗒': { code: 'U+1D5D2', counterpart: 'Y' },
  '𝗓': { code: 'U+1D5D3', counterpart: 'Z' },
  '𝗔': { code: 'U+1D5D4', counterpart: 'A' },
  '𝗕': { code: 'U+1D5D5', counterpart: 'B' },
  '𝗖': { code: 'U+1D5D6', counterpart: 'C' },
  '𝗗': { code: 'U+1D5D7', counterpart: 'D' },
  '𝗘': { code: 'U+1D5D8', counterpart: 'E' },
  '𝗙': { code: 'U+1D5D9', counterpart: 'F' },
  '𝗚': { code: 'U+1D5DA', counterpart: 'G' },
  '𝗛': { code: 'U+1D5DB', counterpart: 'H' },
  '𝗜': { code: 'U+1D5DC', counterpart: 'I' },
  '𝗝': { code: 'U+1D5DD', counterpart: 'J' },
  '𝗞': { code: 'U+1D5DE', counterpart: 'K' },
  '𝗟': { code: 'U+1D5DF', counterpart: 'L' },
  '𝗠': { code: 'U+1D5E0', counterpart: 'M' },
  '𝗡': { code: 'U+1D5E1', counterpart: 'N' },
  '𝗢': { code: 'U+1D5E2', counterpart: 'O' },
  '𝗣': { code: 'U+1D5E3', counterpart: 'P' },
  '𝗤': { code: 'U+1D5E4', counterpart: 'Q' },
  '𝗥': { code: 'U+1D5E5', counterpart: 'R' },
  '𝗦': { code: 'U+1D5E6', counterpart: 'S' },
  '𝗧': { code: 'U+1D5E7', counterpart: 'T' },
  '𝗨': { code: 'U+1D5E8', counterpart: 'U' },
  '𝗩': { code: 'U+1D5E9', counterpart: 'V' },
  '𝗪': { code: 'U+1D5EA', counterpart: 'W' },
  '𝗫': { code: 'U+1D5EB', counterpart: 'X' },
  '𝗬': { code: 'U+1D5EC', counterpart: 'Y' },
  '𝗭': { code: 'U+1D5ED', counterpart: 'Z' },
  '𝗮': { code: 'U+1D5EE', counterpart: 'A' },
  '𝗯': { code: 'U+1D5EF', counterpart: 'B' },
  '𝗰': { code: 'U+1D5F0', counterpart: 'C' },
  '𝗱': { code: 'U+1D5F1', counterpart: 'D' },
  '𝗲': { code: 'U+1D5F2', counterpart: 'E' },
  '𝗳': { code: 'U+1D5F3', counterpart: 'F' },
  '𝗴': { code: 'U+1D5F4', counterpart: 'G' },
  '𝗵': { code: 'U+1D5F5', counterpart: 'H' },
  '𝗶': { code: 'U+1D5F6', counterpart: 'I' },
  '𝗷': { code: 'U+1D5F7', counterpart: 'J' },
  '𝗸': { code: 'U+1D5F8', counterpart: 'K' },
  '𝗹': { code: 'U+1D5F9', counterpart: 'L' },
  '𝗺': { code: 'U+1D5FA', counterpart: 'M' },
  '𝗻': { code: 'U+1D5FB', counterpart: 'N' },
  '𝗼': { code: 'U+1D5FC', counterpart: 'O' },
  '𝗽': { code: 'U+1D5FD', counterpart: 'P' },
  '𝗾': { code: 'U+1D5FE', counterpart: 'Q' },
  '𝗿': { code: 'U+1D5FF', counterpart: 'R' },
  '𝘀': { code: 'U+1D600', counterpart: 'S' },
  '𝘁': { code: 'U+1D601', counterpart: 'T' },
  '𝘂': { code: 'U+1D602', counterpart: 'U' },
  '𝘃': { code: 'U+1D603', counterpart: 'V' },
  '𝘄': { code: 'U+1D604', counterpart: 'W' },
  '𝘅': { code: 'U+1D605', counterpart: 'X' },
  '𝘆': { code: 'U+1D606', counterpart: 'Y' },
  '𝘇': { code: 'U+1D607', counterpart: 'Z' },
  '𝘈': { code: 'U+1D608', counterpart: 'A' },
  '𝘉': { code: 'U+1D609', counterpart: 'B' },
  '𝘊': { code: 'U+1D60A', counterpart: 'C' },
  '𝘋': { code: 'U+1D60B', counterpart: 'D' },
  '𝘌': { code: 'U+1D60C', counterpart: 'E' },
  '𝘍': { code: 'U+1D60D', counterpart: 'F' },
  '𝘎': { code: 'U+1D60E', counterpart: 'G' },
  '𝘏': { code: 'U+1D60F', counterpart: 'H' },
  '𝘐': { code: 'U+1D610', counterpart: 'I' },
  '𝘑': { code: 'U+1D611', counterpart: 'J' },
  '𝘒': { code: 'U+1D612', counterpart: 'K' },
  '𝘓': { code: 'U+1D613', counterpart: 'L' },
  '𝘔': { code: 'U+1D614', counterpart: 'M' },
  '𝘕': { code: 'U+1D615', counterpart: 'N' },
  '𝘖': { code: 'U+1D616', counterpart: 'O' },
  '𝘗': { code: 'U+1D617', counterpart: 'P' },
  '𝘘': { code: 'U+1D618', counterpart: 'Q' },
  '𝘙': { code: 'U+1D619', counterpart: 'R' },
  '𝘚': { code: 'U+1D61A', counterpart: 'S' },
  '𝘛': { code: 'U+1D61B', counterpart: 'T' },
  '𝘜': { code: 'U+1D61C', counterpart: 'U' },
  '𝘝': { code: 'U+1D61D', counterpart: 'V' },
  '𝘞': { code: 'U+1D61E', counterpart: 'W' },
  '𝘟': { code: 'U+1D61F', counterpart: 'X' },
  '𝘠': { code: 'U+1D620', counterpart: 'Y' },
  '𝘡': { code: 'U+1D621', counterpart: 'Z' },
  '𝘢': { code: 'U+1D622', counterpart: 'A' },
  '𝘣': { code: 'U+1D623', counterpart: 'B' },
  '𝘤': { code: 'U+1D624', counterpart: 'C' },
  '𝘥': { code: 'U+1D625', counterpart: 'D' },
  '𝘦': { code: 'U+1D626', counterpart: 'E' },
  '𝘧': { code: 'U+1D627', counterpart: 'F' },
  '𝘨': { code: 'U+1D628', counterpart: 'G' },
  '𝘩': { code: 'U+1D629', counterpart: 'H' },
  '𝘪': { code: 'U+1D62A', counterpart: 'I' },
  '𝘫': { code: 'U+1D62B', counterpart: 'J' },
  '𝘬': { code: 'U+1D62C', counterpart: 'K' },
  '𝘭': { code: 'U+1D62D', counterpart: 'L' },
  '𝘮': { code: 'U+1D62E', counterpart: 'M' },
  '𝘯': { code: 'U+1D62F', counterpart: 'N' },
  '𝘰': { code: 'U+1D630', counterpart: 'O' },
  '𝘱': { code: 'U+1D631', counterpart: 'P' },
  '𝘲': { code: 'U+1D632', counterpart: 'Q' },
  '𝘳': { code: 'U+1D633', counterpart: 'R' },
  '𝘴': { code: 'U+1D634', counterpart: 'S' },
  '𝘵': { code: 'U+1D635', counterpart: 'T' },
  '𝘶': { code: 'U+1D636', counterpart: 'U' },
  '𝘷': { code: 'U+1D637', counterpart: 'V' },
  '𝘸': { code: 'U+1D638', counterpart: 'W' },
  '𝘹': { code: 'U+1D639', counterpart: 'X' },
  '𝘺': { code: 'U+1D63A', counterpart: 'Y' },
  '𝘻': { code: 'U+1D63B', counterpart: 'Z' },
  '𝘼': { code: 'U+1D63C', counterpart: 'A' },
  '𝘽': { code: 'U+1D63D', counterpart: 'B' },
  '𝘾': { code: 'U+1D63E', counterpart: 'C' },
  '𝘿': { code: 'U+1D63F', counterpart: 'D' },
  '𝙀': { code: 'U+1D640', counterpart: 'E' },
  '𝙁': { code: 'U+1D641', counterpart: 'F' },
  '𝙂': { code: 'U+1D642', counterpart: 'G' },
  '𝙃': { code: 'U+1D643', counterpart: 'H' },
  '𝙄': { code: 'U+1D644', counterpart: 'I' },
  '𝙅': { code: 'U+1D645', counterpart: 'J' },
  '𝙆': { code: 'U+1D646', counterpart: 'K' },
  '𝙇': { code: 'U+1D647', counterpart: 'L' },
  '𝙈': { code: 'U+1D648', counterpart: 'M' },
  '𝙉': { code: 'U+1D649', counterpart: 'N' },
  '𝙊': { code: 'U+1D64A', counterpart: 'O' },
  '𝙋': { code: 'U+1D64B', counterpart: 'P' },
  '𝙌': { code: 'U+1D64C', counterpart: 'Q' },
  '𝙍': { code: 'U+1D64D', counterpart: 'R' },
  '𝙎': { code: 'U+1D64E', counterpart: 'S' },
  '𝙏': { code: 'U+1D64F', counterpart: 'T' },
  '𝙐': { code: 'U+1D650', counterpart: 'U' },
  '𝙑': { code: 'U+1D651', counterpart: 'V' },
  '𝙒': { code: 'U+1D652', counterpart: 'W' },
  '𝙓': { code: 'U+1D653', counterpart: 'X' },
  '𝙔': { code: 'U+1D654', counterpart: 'Y' },
  '𝙕': { code: 'U+1D655', counterpart: 'Z' },
  '𝙖': { code: 'U+1D656', counterpart: 'A' },
  '𝙗': { code: 'U+1D657', counterpart: 'B' },
  '𝙘': { code: 'U+1D658', counterpart: 'C' },
  '𝙙': { code: 'U+1D659', counterpart: 'D' },
  '𝙚': { code: 'U+1D65A', counterpart: 'E' },
  '𝙛': { code: 'U+1D65B', counterpart: 'F' },
  '𝙜': { code: 'U+1D65C', counterpart: 'G' },
  '𝙝': { code: 'U+1D65D', counterpart: 'H' },
  '𝙞': { code: 'U+1D65E', counterpart: 'I' },
  '𝙟': { code: 'U+1D65F', counterpart: 'J' },
  '𝙠': { code: 'U+1D660', counterpart: 'K' },
  '𝙡': { code: 'U+1D661', counterpart: 'L' },
  '𝙢': { code: 'U+1D662', counterpart: 'M' },
  '𝙣': { code: 'U+1D663', counterpart: 'N' },
  '𝙤': { code: 'U+1D664', counterpart: 'O' },
  '𝙥': { code: 'U+1D665', counterpart: 'P' },
  '𝙦': { code: 'U+1D666', counterpart: 'Q' },
  '𝙧': { code: 'U+1D667', counterpart: 'R' },
  '𝙨': { code: 'U+1D668', counterpart: 'S' },
  '𝙩': { code: 'U+1D669', counterpart: 'T' },
  '𝙪': { code: 'U+1D66A', counterpart: 'U' },
  '𝙫': { code: 'U+1D66B', counterpart: 'V' },
  '𝙬': { code: 'U+1D66C', counterpart: 'W' },
  '𝙭': { code: 'U+1D66D', counterpart: 'X' },
  '𝙮': { code: 'U+1D66E', counterpart: 'Y' },
  '𝙯': { code: 'U+1D66F', counterpart: 'Z' },
  '𝙰': { code: 'U+1D670', counterpart: 'A' },
  '𝙱': { code: 'U+1D671', counterpart: 'B' },
  '𝙲': { code: 'U+1D672', counterpart: 'C' },
  '𝙳': { code: 'U+1D673', counterpart: 'D' },
  '𝙴': { code: 'U+1D674', counterpart: 'E' },
  '𝙵': { code: 'U+1D675', counterpart: 'F' },
  '𝙶': { code: 'U+1D676', counterpart: 'G' },
  '𝙷': { code: 'U+1D677', counterpart: 'H' },
  '𝙸': { code: 'U+1D678', counterpart: 'I' },
  '𝙹': { code: 'U+1D679', counterpart: 'J' },
  '𝙺': { code: 'U+1D67A', counterpart: 'K' },
  '𝙻': { code: 'U+1D67B', counterpart: 'L' },
  '𝙼': { code: 'U+1D67C', counterpart: 'M' },
  '𝙽': { code: 'U+1D67D', counterpart: 'N' },
  '𝙾': { code: 'U+1D67E', counterpart: 'O' },
  '𝙿': { code: 'U+1D67F', counterpart: 'P' },
  '𝚀': { code: 'U+1D680', counterpart: 'Q' },
  '𝚁': { code: 'U+1D681', counterpart: 'R' },
  '𝚂': { code: 'U+1D682', counterpart: 'S' },
  '𝚃': { code: 'U+1D683', counterpart: 'T' },
  '𝚄': { code: 'U+1D684', counterpart: 'U' },
  '𝚅': { code: 'U+1D685', counterpart: 'V' },
  '𝚆': { code: 'U+1D686', counterpart: 'W' },
  '𝚇': { code: 'U+1D687', counterpart: 'X' },
  '𝚈': { code: 'U+1D688', counterpart: 'Y' },
  '𝚉': { code: 'U+1D689', counterpart: 'Z' },
  '𝚊': { code: 'U+1D68A', counterpart: 'A' },
  '𝚋': { code: 'U+1D68B', counterpart: 'B' },
  '𝚌': { code: 'U+1D68C', counterpart: 'C' },
  '𝚍': { code: 'U+1D68D', counterpart: 'D' },
  '𝚎': { code: 'U+1D68E', counterpart: 'E' },
  '𝚏': { code: 'U+1D68F', counterpart: 'F' },
  '𝚐': { code: 'U+1D690', counterpart: 'G' },
  '𝚑': { code: 'U+1D691', counterpart: 'H' },
  '𝚒': { code: 'U+1D692', counterpart: 'I' },
  '𝚓': { code: 'U+1D693', counterpart: 'J' },
  '𝚔': { code: 'U+1D694', counterpart: 'K' },
  '𝚕': { code: 'U+1D695', counterpart: 'L' },
  '𝚖': { code: 'U+1D696', counterpart: 'M' },
  '𝚗': { code: 'U+1D697', counterpart: 'N' },
  '𝚘': { code: 'U+1D698', counterpart: 'O' },
  '𝚙': { code: 'U+1D699', counterpart: 'P' },
  '𝚚': { code: 'U+1D69A', counterpart: 'Q' },
  '𝚛': { code: 'U+1D69B', counterpart: 'R' },
  '𝚜': { code: 'U+1D69C', counterpart: 'S' },
  '𝚝': { code: 'U+1D69D', counterpart: 'T' },
  '𝚞': { code: 'U+1D69E', counterpart: 'U' },
  '𝚟': { code: 'U+1D69F', counterpart: 'V' },
  '𝚠': { code: 'U+1D6A0', counterpart: 'W' },
  '𝚡': { code: 'U+1D6A1', counterpart: 'X' },
  '𝚢': { code: 'U+1D6A2', counterpart: 'Y' },
  '𝚣': { code: 'U+1D6A3', counterpart: 'Z' },
  '𝚤': { code: 'U+1D6A4', counterpart: 'I' },
  '𝚥': { code: 'U+1D6A5', counterpart: 'J' },

  // Enclosed Alphanumeric Supplement Block
  // https://charbase.com/block/enclosed-alphanumeric-supplement
  '🄐': { code: 'U+1F110', counterpart: 'A' },
  '🄑': { code: 'U+1F111', counterpart: 'B' },
  '🄒': { code: 'U+1F112', counterpart: 'C' },
  '🄓': { code: 'U+1F113', counterpart: 'D' },
  '🄔': { code: 'U+1F114', counterpart: 'E' },
  '🄕': { code: 'U+1F115', counterpart: 'F' },
  '🄖': { code: 'U+1F116', counterpart: 'G' },
  '🄗': { code: 'U+1F117', counterpart: 'H' },
  '🄘': { code: 'U+1F118', counterpart: 'I' },
  '🄙': { code: 'U+1F119', counterpart: 'J' },
  '🄚': { code: 'U+1F11A', counterpart: 'K' },
  '🄛': { code: 'U+1F11B', counterpart: 'L' },
  '🄜': { code: 'U+1F11C', counterpart: 'M' },
  '🄝': { code: 'U+1F11D', counterpart: 'N' },
  '🄞': { code: 'U+1F11E', counterpart: 'O' },
  '🄟': { code: 'U+1F11F', counterpart: 'P' },
  '🄠': { code: 'U+1F120', counterpart: 'Q' },
  '🄡': { code: 'U+1F121', counterpart: 'R' },
  '🄢': { code: 'U+1F122', counterpart: 'S' },
  '🄣': { code: 'U+1F123', counterpart: 'T' },
  '🄤': { code: 'U+1F124', counterpart: 'U' },
  '🄥': { code: 'U+1F125', counterpart: 'V' },
  '🄦': { code: 'U+1F126', counterpart: 'W' },
  '🄧': { code: 'U+1F127', counterpart: 'X' },
  '🄨': { code: 'U+1F128', counterpart: 'Y' },
  '🄩': { code: 'U+1F129', counterpart: 'Z' },
  '🄪': { code: 'U+1F12A', counterpart: 'S' },
  '🄫': { code: 'U+1F12B', counterpart: 'C' },
  '🄬': { code: 'U+1F12C', counterpart: 'R' },
  '🄭': { code: 'U+1F12D', counterpart: 'CIRCLED CD' },
  '🄮': { code: 'U+1F12E', counterpart: 'CIRCLED WZ' },
  '🄰': { code: 'U+1F130', counterpart: 'A' },
  '🄱': { code: 'U+1F131', counterpart: 'B' },
  '🄲': { code: 'U+1F132', counterpart: 'C' },
  '🄳': { code: 'U+1F133', counterpart: 'D' },
  '🄴': { code: 'U+1F134', counterpart: 'E' },
  '🄵': { code: 'U+1F135', counterpart: 'F' },
  '🄶': { code: 'U+1F136', counterpart: 'G' },
  '🄷': { code: 'U+1F137', counterpart: 'H' },
  '🄸': { code: 'U+1F138', counterpart: 'I' },
  '🄹': { code: 'U+1F139', counterpart: 'J' },
  '🄺': { code: 'U+1F13A', counterpart: 'K' },
  '🄻': { code: 'U+1F13B', counterpart: 'L' },
  '🄼': { code: 'U+1F13C', counterpart: 'M' },
  '🄽': { code: 'U+1F13D', counterpart: 'N' },
  '🄾': { code: 'U+1F13E', counterpart: 'O' },
  '🄿': { code: 'U+1F13F', counterpart: 'P' },
  '🅀': { code: 'U+1F140', counterpart: 'Q' },
  '🅁': { code: 'U+1F141', counterpart: 'R' },
  '🅂': { code: 'U+1F142', counterpart: 'S' },
  '🅃': { code: 'U+1F143', counterpart: 'T' },
  '🅄': { code: 'U+1F144', counterpart: 'U' },
  '🅅': { code: 'U+1F145', counterpart: 'V' },
  '🅆': { code: 'U+1F146', counterpart: 'W' },
  '🅇': { code: 'U+1F147', counterpart: 'X' },
  '🅈': { code: 'U+1F148', counterpart: 'Y' },
  '🅉': { code: 'U+1F149', counterpart: 'Z' },
  '🅊': { code: 'U+1F14A', counterpart: 'HV' },
  '🅋': { code: 'U+1F14B', counterpart: 'MV' },
  '🅌': { code: 'U+1F14C', counterpart: 'SD' },
  '🅍': { code: 'U+1F14D', counterpart: 'SS' },
  '🅎': { code: 'U+1F14E', counterpart: 'PPV' },
  '🅏': { code: 'U+1F14F', counterpart: 'WC' },
  '🅐': { code: 'U+1F150', counterpart: 'A' },
  '🅑': { code: 'U+1F151', counterpart: 'B' },
  '🅒': { code: 'U+1F152', counterpart: 'C' },
  '🅓': { code: 'U+1F153', counterpart: 'D' },
  '🅔': { code: 'U+1F154', counterpart: 'E' },
  '🅕': { code: 'U+1F155', counterpart: 'F' },
  '🅖': { code: 'U+1F156', counterpart: 'G' },
  '🅗': { code: 'U+1F157', counterpart: 'H' },
  '🅘': { code: 'U+1F158', counterpart: 'I' },
  '🅙': { code: 'U+1F159', counterpart: 'J' },
  '🅚': { code: 'U+1F15A', counterpart: 'K' },
  '🅛': { code: 'U+1F15B', counterpart: 'L' },
  '🅜': { code: 'U+1F15C', counterpart: 'M' },
  '🅝': { code: 'U+1F15D', counterpart: 'N' },
  '🅞': { code: 'U+1F15E', counterpart: 'O' },
  '🅟': { code: 'U+1F15F', counterpart: 'P' },
  '🅠': { code: 'U+1F160', counterpart: 'Q' },
  '🅡': { code: 'U+1F161', counterpart: 'R' },
  '🅢': { code: 'U+1F162', counterpart: 'S' },
  '🅣': { code: 'U+1F163', counterpart: 'T' },
  '🅤': { code: 'U+1F164', counterpart: 'U' },
  '🅥': { code: 'U+1F165', counterpart: 'V' },
  '🅦': { code: 'U+1F166', counterpart: 'W' },
  '🅧': { code: 'U+1F167', counterpart: 'X' },
  '🅨': { code: 'U+1F168', counterpart: 'Y' },
  '🅩': { code: 'U+1F169', counterpart: 'Z' },
  '🅪': { code: 'U+1F16A', counterpart: 'MC SIGN' },
  '🅫': { code: 'U+1F16B', counterpart: 'MD SIGN' },
  '🅰': { code: 'U+1F170', counterpart: 'A' },
  '🅱': { code: 'U+1F171', counterpart: 'B' },
  '🅲': { code: 'U+1F172', counterpart: 'C' },
  '🅳': { code: 'U+1F173', counterpart: 'D' },
  '🅴': { code: 'U+1F174', counterpart: 'E' },
  '🅵': { code: 'U+1F175', counterpart: 'F' },
  '🅶': { code: 'U+1F176', counterpart: 'G' },
  '🅷': { code: 'U+1F177', counterpart: 'H' },
  '🅸': { code: 'U+1F178', counterpart: 'I' },
  '🅹': { code: 'U+1F179', counterpart: 'J' },
  '🅺': { code: 'U+1F17A', counterpart: 'K' },
  '🅻': { code: 'U+1F17B', counterpart: 'L' },
  '🅼': { code: 'U+1F17C', counterpart: 'M' },
  '🅽': { code: 'U+1F17D', counterpart: 'N' },
  '🅾': { code: 'U+1F17E', counterpart: 'O' },
  '🅿': { code: 'U+1F17F', counterpart: 'P' },
  '🆀': { code: 'U+1F180', counterpart: 'Q' },
  '🆁': { code: 'U+1F181', counterpart: 'R' },
  '🆂': { code: 'U+1F182', counterpart: 'S' },
  '🆃': { code: 'U+1F183', counterpart: 'T' },
  '🆄': { code: 'U+1F184', counterpart: 'U' },
  '🆅': { code: 'U+1F185', counterpart: 'V' },
  '🆆': { code: 'U+1F186', counterpart: 'W' },
  '🆇': { code: 'U+1F187', counterpart: 'X' },
  '🆈': { code: 'U+1F188', counterpart: 'Y' },
  '🆉': { code: 'U+1F189', counterpart: 'Z' },
  '🆊': { code: 'U+1F18A', counterpart: 'P' },
  '🆋': { code: 'U+1F18B', counterpart: 'IC' },
  '🆌': { code: 'U+1F18C', counterpart: 'PA' },
  '🆍': { code: 'U+1F18D', counterpart: 'SA' },
  '🆎': { code: 'U+1F18E', counterpart: 'AB' },
  '🆏': { code: 'U+1F18F', counterpart: 'WC' },
  '🆐': { code: 'U+1F190', counterpart: 'DJ' },
  '🆑': { code: 'U+1F191', counterpart: 'CL' },
  '🆒': { code: 'U+1F192', counterpart: 'COOL' },
  '🆓': { code: 'U+1F193', counterpart: 'FREE' },
  '🆔': { code: 'U+1F194', counterpart: 'ID' },
  '🆕': { code: 'U+1F195', counterpart: 'NEW' },
  '🆖': { code: 'U+1F196', counterpart: 'NG' },
  '🆗': { code: 'U+1F197', counterpart: 'OK' },
  '🆘': { code: 'U+1F198', counterpart: 'SOS' },
  '🆙': { code: 'U+1F199', counterpart: 'UP' },
  '🆚': { code: 'U+1F19A', counterpart: 'VS' },
  '🇦': { code: 'U+1F1E6', counterpart: 'A' },
  '🇧': { code: 'U+1F1E7', counterpart: 'B' },
  '🇨': { code: 'U+1F1E8', counterpart: 'C' },
  '🇩': { code: 'U+1F1E9', counterpart: 'D' },
  '🇪': { code: 'U+1F1EA', counterpart: 'E' },
  '🇫': { code: 'U+1F1EB', counterpart: 'F' },
  '🇬': { code: 'U+1F1EC', counterpart: 'G' },
  '🇭': { code: 'U+1F1ED', counterpart: 'H' },
  '🇮': { code: 'U+1F1EE', counterpart: 'I' },
  '🇯': { code: 'U+1F1EF', counterpart: 'J' },
  '🇰': { code: 'U+1F1F0', counterpart: 'K' },
  '🇱': { code: 'U+1F1F1', counterpart: 'L' },
  '🇲': { code: 'U+1F1F2', counterpart: 'M' },
  '🇳': { code: 'U+1F1F3', counterpart: 'N' },
  '🇴': { code: 'U+1F1F4', counterpart: 'O' },
  '🇵': { code: 'U+1F1F5', counterpart: 'P' },
  '🇶': { code: 'U+1F1F6', counterpart: 'Q' },
  '🇷': { code: 'U+1F1F7', counterpart: 'R' },
  '🇸': { code: 'U+1F1F8', counterpart: 'S' },
  '🇹': { code: 'U+1F1F9', counterpart: 'T' },
  '🇺': { code: 'U+1F1FA', counterpart: 'U' },
  '🇻': { code: 'U+1F1FB', counterpart: 'V' },
  '🇼': { code: 'U+1F1FC', counterpart: 'W' },
  '🇽': { code: 'U+1F1FD', counterpart: 'X' },
  '🇾': { code: 'U+1F1FE', counterpart: 'Y' },
  '🇿': { code: 'U+1F1FF', counterpart: 'Z' },
}

export const NumberCounterparts = {
  // Mathematical Alphanumeric Symbols Block
  // https://charbase.com/block/mathematical-alphanumeric-symbols
  '𝟎': { code: 'U+1D7CE', counterpart: 0 },
  '𝟏': { code: 'U+1D7CF', counterpart: 1 },
  '𝟐': { code: 'U+1D7D0', counterpart: 2 },
  '𝟑': { code: 'U+1D7D1', counterpart: 3 },
  '𝟒': { code: 'U+1D7D2', counterpart: 4 },
  '𝟓': { code: 'U+1D7D3', counterpart: 5 },
  '𝟔': { code: 'U+1D7D4', counterpart: 6 },
  '𝟕': { code: 'U+1D7D5', counterpart: 7 },
  '𝟖': { code: 'U+1D7D6', counterpart: 8 },
  '𝟗': { code: 'U+1D7D7', counterpart: 9 },
  '𝟘': { code: 'U+1D7D8', counterpart: 0 },
  '𝟙': { code: 'U+1D7D9', counterpart: 1 },
  '𝟚': { code: 'U+1D7DA', counterpart: 2 },
  '𝟛': { code: 'U+1D7DB', counterpart: 3 },
  '𝟜': { code: 'U+1D7DC', counterpart: 4 },
  '𝟝': { code: 'U+1D7DD', counterpart: 5 },
  '𝟞': { code: 'U+1D7DE', counterpart: 6 },
  '𝟟': { code: 'U+1D7DF', counterpart: 7 },
  '𝟠': { code: 'U+1D7E0', counterpart: 8 },
  '𝟡': { code: 'U+1D7E1', counterpart: 9 },
  '𝟢': { code: 'U+1D7E2', counterpart: 0 },
  '𝟣': { code: 'U+1D7E3', counterpart: 1 },
  '𝟤': { code: 'U+1D7E4', counterpart: 2 },
  '𝟥': { code: 'U+1D7E5', counterpart: 3 },
  '𝟦': { code: 'U+1D7E6', counterpart: 4 },
  '𝟧': { code: 'U+1D7E7', counterpart: 5 },
  '𝟨': { code: 'U+1D7E8', counterpart: 6 },
  '𝟩': { code: 'U+1D7E9', counterpart: 7 },
  '𝟪': { code: 'U+1D7EA', counterpart: 8 },
  '𝟫': { code: 'U+1D7EB', counterpart: 9 },
  '𝟬': { code: 'U+1D7EC', counterpart: 0 },
  '𝟭': { code: 'U+1D7ED', counterpart: 1 },
  '𝟮': { code: 'U+1D7EE', counterpart: 2 },
  '𝟯': { code: 'U+1D7EF', counterpart: 3 },
  '𝟰': { code: 'U+1D7F0', counterpart: 4 },
  '𝟱': { code: 'U+1D7F1', counterpart: 5 },
  '𝟲': { code: 'U+1D7F2', counterpart: 6 },
  '𝟳': { code: 'U+1D7F3', counterpart: 7 },
  '𝟴': { code: 'U+1D7F4', counterpart: 8 },
  '𝟵': { code: 'U+1D7F5', counterpart: 9 },
  '𝟶': { code: 'U+1D7F6', counterpart: 0 },
  '𝟷': { code: 'U+1D7F7', counterpart: 1 },
  '𝟸': { code: 'U+1D7F8', counterpart: 2 },
  '𝟹': { code: 'U+1D7F9', counterpart: 3 },
  '𝟺': { code: 'U+1D7FA', counterpart: 4 },
  '𝟻': { code: 'U+1D7FB', counterpart: 5 },
  '𝟼': { code: 'U+1D7FC', counterpart: 6 },
  '𝟽': { code: 'U+1D7FD', counterpart: 7 },
  '𝟾': { code: 'U+1D7FE', counterpart: 8 },
  '𝟿': { code: 'U+1D7FF', counterpart: 9 },
  '➀': { counterpart: 1 },
  '➁': { counterpart: 2 },
  '➂': { counterpart: 3 },
  '➃': { counterpart: 4 },
  '➄': { counterpart: 5 },
  '➅': { counterpart: 6 },
  '➆': { counterpart: 7 },
  '➇': { counterpart: 8 },
  '➈': { counterpart: 9 },
  '➉': { counterpart: 10 },
  '➊': { counterpart: 1 },
  '➋': { counterpart: 2 },
  '➌': { counterpart: 3 },
  '➍': { counterpart: 4 },
  '➎': { counterpart: 5 },
  '➏': { counterpart: 6 },
  '➐': { counterpart: 7 },
  '➑': { counterpart: 8 },
  '➒': { counterpart: 9 },
  '➓': { counterpart: 10 },
  '⓵': { counterpart: 1 },
  '⓶': { counterpart: 2 },
  '⓷': { counterpart: 3 },
  '⓸': { counterpart: 4 },
  '⓹': { counterpart: 5 },
  '⓺': { counterpart: 6 },
  '⓻': { counterpart: 7 },
  '⓼': { counterpart: 8 },
  '⓽': { counterpart: 9 },
  '⓾': { counterpart: 10 },
  '⓿': { counterpart: 0 },
  '❶': { counterpart: 1 },
  '❷': { counterpart: 2 },
  '❸': { counterpart: 3 },
  '❹': { counterpart: 4 },
  '❺': { counterpart: 5 },
  '❻': { counterpart: 6 },
  '❼': { counterpart: 7 },
  '❽': { counterpart: 8 },
  '❾': { counterpart: 9 },
  '❿': { counterpart: 10 },
  '⁰': { counterpart: 0 },
  '¹': { counterpart: 1 },
  '²': { counterpart: 2 },
  '³': { counterpart: 3 },
  '⁴': { counterpart: 4 },
  '⁵': { counterpart: 5 },
  '⁶': { counterpart: 6 },
  '⁷': { counterpart: 7 },
  '⁸': { counterpart: 8 },
  '⁹': { counterpart: 9 },
  '₀': { counterpart: 0 },
  '₁': { counterpart: 1 },
  '₂': { counterpart: 2 },
  '₃': { counterpart: 3 },
  '₄': { counterpart: 4 },
  '₅': { counterpart: 5 },
  '₆': { counterpart: 6 },
  '₇': { counterpart: 7 },
  '₈': { counterpart: 8 },
  '₉': { counterpart: 9 },
  '⓪': { counterpart: 0 },
  '①': { counterpart: 1 },
  '②': { counterpart: 2 },
  '③': { counterpart: 3 },
  '④': { counterpart: 4 },
  '⑤': { counterpart: 5 },
  '⑥': { counterpart: 6 },
  '⑦': { counterpart: 7 },
  '⑧': { counterpart: 8 },
  '⑨': { counterpart: 9 },
  '⑩': { counterpart: 10 },
  '⑪': { counterpart: 11 },
  '⑫': { counterpart: 12 },
  '⑬': { counterpart: 13 },
  '⑭': { counterpart: 14 },
  '⑮': { counterpart: 15 },
  '⑯': { counterpart: 16 },
  '⑰': { counterpart: 17 },
  '⑱': { counterpart: 18 },
  '⑲': { counterpart: 19 },
  '⑳': { counterpart: 20 },
  '⑴': { counterpart: 1 },
  '⑵': { counterpart: 2 },
  '⑶': { counterpart: 3 },
  '⑷': { counterpart: 4 },
  '⑸': { counterpart: 5 },
  '⑹': { counterpart: 6 },
  '⑺': { counterpart: 7 },
  '⑻': { counterpart: 8 },
  '⑼': { counterpart: 9 },
  '⑽': { counterpart: 10 },
  '⑾': { counterpart: 11 },
  '⑿': { counterpart: 12 },
  '⒀': { counterpart: 13 },
  '⒁': { counterpart: 14 },
  '⒂': { counterpart: 15 },
  '⒃': { counterpart: 16 },
  '⒄': { counterpart: 17 },
  '⒅': { counterpart: 18 },
  '⒆': { counterpart: 19 },
  '⒇': { counterpart: 20 },
  '⒈': { counterpart: 1 },
  '⒉': { counterpart: 2 },
  '⒊': { counterpart: 3 },
  '⒋': { counterpart: 4 },
  '⒌': { counterpart: 5 },
  '⒍': { counterpart: 6 },
  '⒎': { counterpart: 7 },
  '⒏': { counterpart: 8 },
  '⒐': { counterpart: 9 },
  '⒑': { counterpart: 10 },
  '⒒': { counterpart: 11 },
  '⒓': { counterpart: 12 },
  '⒔': { counterpart: 13 },
  '⒕': { counterpart: 14 },
  '⒖': { counterpart: 15 },
  '⒗': { counterpart: 16 },
  '⒘': { counterpart: 17 },
  '⒙': { counterpart: 18 },
  '⒚': { counterpart: 19 },
  '⒛': { counterpart: 20 },
  '０': { counterpart: 0 },
  '１': { counterpart: 1 },
  '２': { counterpart: 2 },
  '３': { counterpart: 3 },
  '４': { counterpart: 4 },
  '５': { counterpart: 5 },
  '６': { counterpart: 6 },
  '７': { counterpart: 7 },
  '８': { counterpart: 8 },
  '９': { counterpart: 9 },

  // Enclosed Alphanumeric Supplement Block
  // https://charbase.com/block/enclosed-alphanumeric-supplement
  '🄀': { code: 'U+1F100', counterpart: '0' },
  '🄁': { code: 'U+1F101', counterpart: '0' },
  '🄂': { code: 'U+1F102', counterpart: '1' },
  '🄃': { code: 'U+1F103', counterpart: '2' },
  '🄄': { code: 'U+1F104', counterpart: '3' },
  '🄅': { code: 'U+1F105', counterpart: '4' },
  '🄆': { code: 'U+1F106', counterpart: '5' },
  '🄇': { code: 'U+1F107', counterpart: '6' },
  '🄈': { code: 'U+1F108', counterpart: '7' },
  '🄉': { code: 'U+1F109', counterpart: '8' },
  '🄊': { code: 'U+1F10A', counterpart: '9' },
}

const OtherCounterparts = {
  // Mathematical Alphanumeric Symbols Block
  // https://charbase.com/block/mathematical-alphanumeric-symbols
  '𝚨': { code: 'U+1D6A8', counterpart: 'ALPHA' },
  '𝚩': { code: 'U+1D6A9', counterpart: 'BETA' },
  '𝚪': { code: 'U+1D6AA', counterpart: 'GAMMA' },
  '𝚫': { code: 'U+1D6AB', counterpart: 'DELTA' },
  '𝚬': { code: 'U+1D6AC', counterpart: 'EPSILON' },
  '𝚭': { code: 'U+1D6AD', counterpart: 'ZETA' },
  '𝚮': { code: 'U+1D6AE', counterpart: 'ETA' },
  '𝚯': { code: 'U+1D6AF', counterpart: 'THETA' },
  '𝚰': { code: 'U+1D6B0', counterpart: 'IOTA' },
  '𝚱': { code: 'U+1D6B1', counterpart: 'KAPPA' },
  '𝚲': { code: 'U+1D6B2', counterpart: 'LAMDA' },
  '𝚳': { code: 'U+1D6B3', counterpart: 'MU' },
  '𝚴': { code: 'U+1D6B4', counterpart: 'NU' },
  '𝚵': { code: 'U+1D6B5', counterpart: 'XI' },
  '𝚶': { code: 'U+1D6B6', counterpart: 'OMICRON' },
  '𝚷': { code: 'U+1D6B7', counterpart: 'PI' },
  '𝚸': { code: 'U+1D6B8', counterpart: 'RHO' },
  '𝚹': { code: 'U+1D6B9', counterpart: 'THETA' },
  '𝚺': { code: 'U+1D6BA', counterpart: 'SIGMA' },
  '𝚻': { code: 'U+1D6BB', counterpart: 'TAU' },
  '𝚼': { code: 'U+1D6BC', counterpart: 'UPSILON' },
  '𝚽': { code: 'U+1D6BD', counterpart: 'PHI' },
  '𝚾': { code: 'U+1D6BE', counterpart: 'CHI' },
  '𝚿': { code: 'U+1D6BF', counterpart: 'PSI' },
  '𝛀': { code: 'U+1D6C0', counterpart: 'OMEGA' },
  '𝛁': { code: 'U+1D6C1', counterpart: 'NABLA' },
  '𝛂': { code: 'U+1D6C2', counterpart: 'ALPHA' },
  '𝛃': { code: 'U+1D6C3', counterpart: 'BETA' },
  '𝛄': { code: 'U+1D6C4', counterpart: 'GAMMA' },
  '𝛅': { code: 'U+1D6C5', counterpart: 'DELTA' },
  '𝛆': { code: 'U+1D6C6', counterpart: 'EPSILON' },
  '𝛇': { code: 'U+1D6C7', counterpart: 'ZETA' },
  '𝛈': { code: 'U+1D6C8', counterpart: 'ETA' },
  '𝛉': { code: 'U+1D6C9', counterpart: 'THETA' },
  '𝛊': { code: 'U+1D6CA', counterpart: 'IOTA' },
  '𝛋': { code: 'U+1D6CB', counterpart: 'KAPPA' },
  '𝛌': { code: 'U+1D6CC', counterpart: 'LAMDA' },
  '𝛍': { code: 'U+1D6CD', counterpart: 'MU' },
  '𝛎': { code: 'U+1D6CE', counterpart: 'NU' },
  '𝛏': { code: 'U+1D6CF', counterpart: 'XI' },
  '𝛐': { code: 'U+1D6D0', counterpart: 'OMICRON' },
  '𝛑': { code: 'U+1D6D1', counterpart: 'PI' },
  '𝛒': { code: 'U+1D6D2', counterpart: 'RHO' },
  '𝛓': { code: 'U+1D6D3', counterpart: 'FINAL SIGMA' },
  '𝛔': { code: 'U+1D6D4', counterpart: 'SIGMA' },
  '𝛕': { code: 'U+1D6D5', counterpart: 'TAU' },
  '𝛖': { code: 'U+1D6D6', counterpart: 'UPSILON' },
  '𝛗': { code: 'U+1D6D7', counterpart: 'PHI' },
  '𝛘': { code: 'U+1D6D8', counterpart: 'CHI' },
  '𝛙': { code: 'U+1D6D9', counterpart: 'PSI' },
  '𝛚': { code: 'U+1D6DA', counterpart: 'OMEGA' },
  '𝛛': { code: 'U+1D6DB', counterpart: 'PARTIAL DIFFERENTIAL' },
  '𝛜': { code: 'U+1D6DC', counterpart: 'EPSILON' },
  '𝛝': { code: 'U+1D6DD', counterpart: 'THETA' },
  '𝛞': { code: 'U+1D6DE', counterpart: 'KAPPA' },
  '𝛟': { code: 'U+1D6DF', counterpart: 'PHI' },
  '𝛠': { code: 'U+1D6E0', counterpart: 'RHO' },
  '𝛡': { code: 'U+1D6E1', counterpart: 'PI' },
  '𝛢': { code: 'U+1D6E2', counterpart: 'ALPHA' },
  '𝛣': { code: 'U+1D6E3', counterpart: 'BETA' },
  '𝛤': { code: 'U+1D6E4', counterpart: 'GAMMA' },
  '𝛥': { code: 'U+1D6E5', counterpart: 'DELTA' },
  '𝛦': { code: 'U+1D6E6', counterpart: 'EPSILON' },
  '𝛧': { code: 'U+1D6E7', counterpart: 'ZETA' },
  '𝛨': { code: 'U+1D6E8', counterpart: 'ETA' },
  '𝛩': { code: 'U+1D6E9', counterpart: 'THETA' },
  '𝛪': { code: 'U+1D6EA', counterpart: 'IOTA' },
  '𝛫': { code: 'U+1D6EB', counterpart: 'KAPPA' },
  '𝛬': { code: 'U+1D6EC', counterpart: 'LAMDA' },
  '𝛭': { code: 'U+1D6ED', counterpart: 'MU' },
  '𝛮': { code: 'U+1D6EE', counterpart: 'NU' },
  '𝛯': { code: 'U+1D6EF', counterpart: 'XI' },
  '𝛰': { code: 'U+1D6F0', counterpart: 'OMICRON' },
  '𝛱': { code: 'U+1D6F1', counterpart: 'PI' },
  '𝛲': { code: 'U+1D6F2', counterpart: 'RHO' },
  '𝛳': { code: 'U+1D6F3', counterpart: 'THETA' },
  '𝛴': { code: 'U+1D6F4', counterpart: 'SIGMA' },
  '𝛵': { code: 'U+1D6F5', counterpart: 'TAU' },
  '𝛶': { code: 'U+1D6F6', counterpart: 'UPSILON' },
  '𝛷': { code: 'U+1D6F7', counterpart: 'PHI' },
  '𝛸': { code: 'U+1D6F8', counterpart: 'CHI' },
  '𝛹': { code: 'U+1D6F9', counterpart: 'PSI' },
  '𝛺': { code: 'U+1D6FA', counterpart: 'OMEGA' },
  '𝛻': { code: 'U+1D6FB', counterpart: 'NABLA' },
  '𝛼': { code: 'U+1D6FC', counterpart: 'ALPHA' },
  '𝛽': { code: 'U+1D6FD', counterpart: 'BETA' },
  '𝛾': { code: 'U+1D6FE', counterpart: 'GAMMA' },
  '𝛿': { code: 'U+1D6FF', counterpart: 'DELTA' },
  '𝜀': { code: 'U+1D700', counterpart: 'EPSILON' },
  '𝜁': { code: 'U+1D701', counterpart: 'ZETA' },
  '𝜂': { code: 'U+1D702', counterpart: 'ETA' },
  '𝜃': { code: 'U+1D703', counterpart: 'THETA' },
  '𝜄': { code: 'U+1D704', counterpart: 'IOTA' },
  '𝜅': { code: 'U+1D705', counterpart: 'KAPPA' },
  '𝜆': { code: 'U+1D706', counterpart: 'LAMDA' },
  '𝜇': { code: 'U+1D707', counterpart: 'MU' },
  '𝜈': { code: 'U+1D708', counterpart: 'NU' },
  '𝜉': { code: 'U+1D709', counterpart: 'XI' },
  '𝜊': { code: 'U+1D70A', counterpart: 'OMICRON' },
  '𝜋': { code: 'U+1D70B', counterpart: 'PI' },
  '𝜌': { code: 'U+1D70C', counterpart: 'RHO' },
  '𝜍': { code: 'U+1D70D', counterpart: 'FINAL SIGMA' },
  '𝜎': { code: 'U+1D70E', counterpart: 'SIGMA' },
  '𝜏': { code: 'U+1D70F', counterpart: 'TAU' },
  '𝜐': { code: 'U+1D710', counterpart: 'UPSILON' },
  '𝜑': { code: 'U+1D711', counterpart: 'PHI' },
  '𝜒': { code: 'U+1D712', counterpart: 'CHI' },
  '𝜓': { code: 'U+1D713', counterpart: 'PSI' },
  '𝜔': { code: 'U+1D714', counterpart: 'OMEGA' },
  '𝜕': { code: 'U+1D715', counterpart: 'PARTIAL DIFFERENTIAL' },
  '𝜖': { code: 'U+1D716', counterpart: 'EPSILON' },
  '𝜗': { code: 'U+1D717', counterpart: 'THETA' },
  '𝜘': { code: 'U+1D718', counterpart: 'KAPPA' },
  '𝜙': { code: 'U+1D719', counterpart: 'PHI' },
  '𝜚': { code: 'U+1D71A', counterpart: 'RHO' },
  '𝜛': { code: 'U+1D71B', counterpart: 'PI' },
  '𝜜': { code: 'U+1D71C', counterpart: 'ALPHA' },
  '𝜝': { code: 'U+1D71D', counterpart: 'BETA' },
  '𝜞': { code: 'U+1D71E', counterpart: 'GAMMA' },
  '𝜟': { code: 'U+1D71F', counterpart: 'DELTA' },
  '𝜠': { code: 'U+1D720', counterpart: 'EPSILON' },
  '𝜡': { code: 'U+1D721', counterpart: 'ZETA' },
  '𝜢': { code: 'U+1D722', counterpart: 'ETA' },
  '𝜣': { code: 'U+1D723', counterpart: 'THETA' },
  '𝜤': { code: 'U+1D724', counterpart: 'IOTA' },
  '𝜥': { code: 'U+1D725', counterpart: 'KAPPA' },
  '𝜦': { code: 'U+1D726', counterpart: 'LAMDA' },
  '𝜧': { code: 'U+1D727', counterpart: 'MU' },
  '𝜨': { code: 'U+1D728', counterpart: 'NU' },
  '𝜩': { code: 'U+1D729', counterpart: 'XI' },
  '𝜪': { code: 'U+1D72A', counterpart: 'OMICRON' },
  '𝜫': { code: 'U+1D72B', counterpart: 'PI' },
  '𝜬': { code: 'U+1D72C', counterpart: 'RHO' },
  '𝜭': { code: 'U+1D72D', counterpart: 'THETA' },
  '𝜮': { code: 'U+1D72E', counterpart: 'SIGMA' },
  '𝜯': { code: 'U+1D72F', counterpart: 'TAU' },
  '𝜰': { code: 'U+1D730', counterpart: 'UPSILON' },
  '𝜱': { code: 'U+1D731', counterpart: 'PHI' },
  '𝜲': { code: 'U+1D732', counterpart: 'CHI' },
  '𝜳': { code: 'U+1D733', counterpart: 'PSI' },
  '𝜴': { code: 'U+1D734', counterpart: 'OMEGA' },
  '𝜵': { code: 'U+1D735', counterpart: 'NABLA' },
  '𝜶': { code: 'U+1D736', counterpart: 'ALPHA' },
  '𝜷': { code: 'U+1D737', counterpart: 'BETA' },
  '𝜸': { code: 'U+1D738', counterpart: 'GAMMA' },
  '𝜹': { code: 'U+1D739', counterpart: 'DELTA' },
  '𝜺': { code: 'U+1D73A', counterpart: 'EPSILON' },
  '𝜻': { code: 'U+1D73B', counterpart: 'ZETA' },
  '𝜼': { code: 'U+1D73C', counterpart: 'ETA' },
  '𝜽': { code: 'U+1D73D', counterpart: 'THETA' },
  '𝜾': { code: 'U+1D73E', counterpart: 'IOTA' },
  '𝜿': { code: 'U+1D73F', counterpart: 'KAPPA' },
  '𝝀': { code: 'U+1D740', counterpart: 'LAMDA' },
  '𝝁': { code: 'U+1D741', counterpart: 'MU' },
  '𝝂': { code: 'U+1D742', counterpart: 'NU' },
  '𝝃': { code: 'U+1D743', counterpart: 'XI' },
  '𝝄': { code: 'U+1D744', counterpart: 'OMICRON' },
  '𝝅': { code: 'U+1D745', counterpart: 'PI' },
  '𝝆': { code: 'U+1D746', counterpart: 'RHO' },
  '𝝇': { code: 'U+1D747', counterpart: 'FINAL SIGMA' },
  '𝝈': { code: 'U+1D748', counterpart: 'SIGMA' },
  '𝝉': { code: 'U+1D749', counterpart: 'TAU' },
  '𝝊': { code: 'U+1D74A', counterpart: 'UPSILON' },
  '𝝋': { code: 'U+1D74B', counterpart: 'PHI' },
  '𝝌': { code: 'U+1D74C', counterpart: 'CHI' },
  '𝝍': { code: 'U+1D74D', counterpart: 'PSI' },
  '𝝎': { code: 'U+1D74E', counterpart: 'OMEGA' },
  '𝝏': { code: 'U+1D74F', counterpart: 'PARTIAL DIFFERENTIAL' },
  '𝝐': { code: 'U+1D750', counterpart: 'EPSILON' },
  '𝝑': { code: 'U+1D751', counterpart: 'THETA' },
  '𝝒': { code: 'U+1D752', counterpart: 'KAPPA' },
  '𝝓': { code: 'U+1D753', counterpart: 'PHI' },
  '𝝔': { code: 'U+1D754', counterpart: 'RHO' },
  '𝝕': { code: 'U+1D755', counterpart: 'PI' },
  '𝝖': { code: 'U+1D756', counterpart: 'ALPHA' },
  '𝝗': { code: 'U+1D757', counterpart: 'BETA' },
  '𝝘': { code: 'U+1D758', counterpart: 'GAMMA' },
  '𝝙': { code: 'U+1D759', counterpart: 'DELTA' },
  '𝝚': { code: 'U+1D75A', counterpart: 'EPSILON' },
  '𝝛': { code: 'U+1D75B', counterpart: 'ZETA' },
  '𝝜': { code: 'U+1D75C', counterpart: 'ETA' },
  '𝝝': { code: 'U+1D75D', counterpart: 'THETA' },
  '𝝞': { code: 'U+1D75E', counterpart: 'IOTA' },
  '𝝟': { code: 'U+1D75F', counterpart: 'KAPPA' },
  '𝝠': { code: 'U+1D760', counterpart: 'LAMDA' },
  '𝝡': { code: 'U+1D761', counterpart: 'MU' },
  '𝝢': { code: 'U+1D762', counterpart: 'NU' },
  '𝝣': { code: 'U+1D763', counterpart: 'XI' },
  '𝝤': { code: 'U+1D764', counterpart: 'OMICRON' },
  '𝝥': { code: 'U+1D765', counterpart: 'PI' },
  '𝝦': { code: 'U+1D766', counterpart: 'RHO' },
  '𝝧': { code: 'U+1D767', counterpart: 'THETA' },
  '𝝨': { code: 'U+1D768', counterpart: 'SIGMA' },
  '𝝩': { code: 'U+1D769', counterpart: 'TAU' },
  '𝝪': { code: 'U+1D76A', counterpart: 'UPSILON' },
  '𝝫': { code: 'U+1D76B', counterpart: 'PHI' },
  '𝝬': { code: 'U+1D76C', counterpart: 'CHI' },
  '𝝭': { code: 'U+1D76D', counterpart: 'PSI' },
  '𝝮': { code: 'U+1D76E', counterpart: 'OMEGA' },
  '𝝯': { code: 'U+1D76F', counterpart: 'NABLA' },
  '𝝰': { code: 'U+1D770', counterpart: 'ALPHA' },
  '𝝱': { code: 'U+1D771', counterpart: 'BETA' },
  '𝝲': { code: 'U+1D772', counterpart: 'GAMMA' },
  '𝝳': { code: 'U+1D773', counterpart: 'DELTA' },
  '𝝴': { code: 'U+1D774', counterpart: 'EPSILON' },
  '𝝵': { code: 'U+1D775', counterpart: 'ZETA' },
  '𝝶': { code: 'U+1D776', counterpart: 'ETA' },
  '𝝷': { code: 'U+1D777', counterpart: 'THETA' },
  '𝝸': { code: 'U+1D778', counterpart: 'IOTA' },
  '𝝹': { code: 'U+1D779', counterpart: 'KAPPA' },
  '𝝺': { code: 'U+1D77A', counterpart: 'LAMDA' },
  '𝝻': { code: 'U+1D77B', counterpart: 'MU' },
  '𝝼': { code: 'U+1D77C', counterpart: 'NU' },
  '𝝽': { code: 'U+1D77D', counterpart: 'XI' },
  '𝝾': { code: 'U+1D77E', counterpart: 'OMICRON' },
  '𝝿': { code: 'U+1D77F', counterpart: 'PI' },
  '𝞀': { code: 'U+1D780', counterpart: 'RHO' },
  '𝞁': { code: 'U+1D781', counterpart: 'FINAL SIGMA' },
  '𝞂': { code: 'U+1D782', counterpart: 'SIGMA' },
  '𝞃': { code: 'U+1D783', counterpart: 'TAU' },
  '𝞄': { code: 'U+1D784', counterpart: 'UPSILON' },
  '𝞅': { code: 'U+1D785', counterpart: 'PHI' },
  '𝞆': { code: 'U+1D786', counterpart: 'CHI' },
  '𝞇': { code: 'U+1D787', counterpart: 'PSI' },
  '𝞈': { code: 'U+1D788', counterpart: 'OMEGA' },
  '𝞉': { code: 'U+1D789', counterpart: 'PARTIAL DIFFERENTIAL' },
  '𝞊': { code: 'U+1D78A', counterpart: 'EPSILON' },
  '𝞋': { code: 'U+1D78B', counterpart: 'THETA' },
  '𝞌': { code: 'U+1D78C', counterpart: 'KAPPA' },
  '𝞍': { code: 'U+1D78D', counterpart: 'PHI' },
  '𝞎': { code: 'U+1D78E', counterpart: 'RHO' },
  '𝞏': { code: 'U+1D78F', counterpart: 'PI' },
  '𝞐': { code: 'U+1D790', counterpart: 'ALPHA' },
  '𝞑': { code: 'U+1D791', counterpart: 'BETA' },
  '𝞒': { code: 'U+1D792', counterpart: 'GAMMA' },
  '𝞓': { code: 'U+1D793', counterpart: 'DELTA' },
  '𝞔': { code: 'U+1D794', counterpart: 'EPSILON' },
  '𝞕': { code: 'U+1D795', counterpart: 'ZETA' },
  '𝞖': { code: 'U+1D796', counterpart: 'ETA' },
  '𝞗': { code: 'U+1D797', counterpart: 'THETA' },
  '𝞘': { code: 'U+1D798', counterpart: 'IOTA' },
  '𝞙': { code: 'U+1D799', counterpart: 'KAPPA' },
  '𝞚': { code: 'U+1D79A', counterpart: 'LAMDA' },
  '𝞛': { code: 'U+1D79B', counterpart: 'MU' },
  '𝞜': { code: 'U+1D79C', counterpart: 'NU' },
  '𝞝': { code: 'U+1D79D', counterpart: 'XI' },
  '𝞞': { code: 'U+1D79E', counterpart: 'OMICRON' },
  '𝞟': { code: 'U+1D79F', counterpart: 'PI' },
  '𝞠': { code: 'U+1D7A0', counterpart: 'RHO' },
  '𝞡': { code: 'U+1D7A1', counterpart: 'THETA' },
  '𝞢': { code: 'U+1D7A2', counterpart: 'SIGMA' },
  '𝞣': { code: 'U+1D7A3', counterpart: 'TAU' },
  '𝞤': { code: 'U+1D7A4', counterpart: 'UPSILON' },
  '𝞥': { code: 'U+1D7A5', counterpart: 'PHI' },
  '𝞦': { code: 'U+1D7A6', counterpart: 'CHI' },
  '𝞧': { code: 'U+1D7A7', counterpart: 'PSI' },
  '𝞨': { code: 'U+1D7A8', counterpart: 'OMEGA' },
  '𝞩': { code: 'U+1D7A9', counterpart: 'NABLA' },
  '𝞪': { code: 'U+1D7AA', counterpart: 'ALPHA' },
  '𝞫': { code: 'U+1D7AB', counterpart: 'BETA' },
  '𝞬': { code: 'U+1D7AC', counterpart: 'GAMMA' },
  '𝞭': { code: 'U+1D7AD', counterpart: 'DELTA' },
  '𝞮': { code: 'U+1D7AE', counterpart: 'EPSILON' },
  '𝞯': { code: 'U+1D7AF', counterpart: 'ZETA' },
  '𝞰': { code: 'U+1D7B0', counterpart: 'ETA' },
  '𝞱': { code: 'U+1D7B1', counterpart: 'THETA' },
  '𝞲': { code: 'U+1D7B2', counterpart: 'IOTA' },
  '𝞳': { code: 'U+1D7B3', counterpart: 'KAPPA' },
  '𝞴': { code: 'U+1D7B4', counterpart: 'LAMDA' },
  '𝞵': { code: 'U+1D7B5', counterpart: 'MU' },
  '𝞶': { code: 'U+1D7B6', counterpart: 'NU' },
  '𝞷': { code: 'U+1D7B7', counterpart: 'XI' },
  '𝞸': { code: 'U+1D7B8', counterpart: 'OMICRON' },
  '𝞹': { code: 'U+1D7B9', counterpart: 'PI' },
  '𝞺': { code: 'U+1D7BA', counterpart: 'RHO' },
  '𝞻': { code: 'U+1D7BB', counterpart: 'FINAL SIGMA' },
  '𝞼': { code: 'U+1D7BC', counterpart: 'SIGMA' },
  '𝞽': { code: 'U+1D7BD', counterpart: 'TAU' },
  '𝞾': { code: 'U+1D7BE', counterpart: 'UPSILON' },
  '𝞿': { code: 'U+1D7BF', counterpart: 'PHI' },
  '𝟀': { code: 'U+1D7C0', counterpart: 'CHI' },
  '𝟁': { code: 'U+1D7C1', counterpart: 'PSI' },
  '𝟂': { code: 'U+1D7C2', counterpart: 'OMEGA' },
  '𝟃': { code: 'U+1D7C3', counterpart: 'PARTIAL DIFFERENTIAL' },
  '𝟄': { code: 'U+1D7C4', counterpart: 'EPSILON' },
  '𝟅': { code: 'U+1D7C5', counterpart: 'THETA' },
  '𝟆': { code: 'U+1D7C6', counterpart: 'KAPPA' },
  '𝟇': { code: 'U+1D7C7', counterpart: 'PHI' },
  '𝟈': { code: 'U+1D7C8', counterpart: 'RHO' },
  '𝟉': { code: 'U+1D7C9', counterpart: 'PI' },
  '𝟊': { code: 'U+1D7CA', counterpart: 'DIGAMMA' },
  '𝟋': { code: 'U+1D7CB', counterpart: 'DIGAMMA' },
}

export const PlusSymbolCounterparts = {
  '±': { counterpart: '+' },
  十: { counterpart: '+' },
  '⼗': { counterpart: '+' },
  '㈩': { counterpart: '+' },
  '㊉': { counterpart: '+' },
  '✝': { counterpart: '+' },
  '✞': { counterpart: '+' },
  '✟': { counterpart: '+' },
  '♱': { counterpart: '+' },
  '♰': { counterpart: '+' },
  '☩': { counterpart: '+' },
  '✙': { counterpart: '+' },
  '✚': { counterpart: '+' },
  '✛': { counterpart: '+' },
  '✜': { counterpart: '+' },
  '✠': { counterpart: '+' },
  '⁜': { counterpart: '+' },
}

// 'ⁱ', 'ₐ', 'ₑ', 'ₒ', 'ₓ', 'ₔ'

const Counterparts = {
  ...LetterCounterparts,
  ...NumberCounterparts,
  ...PlusSymbolCounterparts,
}

export default Counterparts
